robot_ns:
  servo_motor:
    type: pm_motor
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
    
    inverter:
      joint_a1: {umax: 48.0}
      joint_a2: {umax: 48.0}
      joint_a3: {umax: 48.0}
      joint_a4: {umax: 48.0}
      joint_a5: {umax: 48.0}
      joint_a6: {umax: 48.0}
      joint_a7: {umax: 48.0}
    
    motor_parameters: 
      joint_a1: {r: 20.0, l: 0.0, km: 10.0}
      joint_a2: {r: 20.0, l: 0.0, km: 10.0}
      joint_a3: {r: 20.0, l: 0.0, km: 10.0}
      joint_a4: {r: 20.0, l: 0.0, km: 10.0}
      joint_a5: {r: 20.0, l: 0.0, km: 10.0}
      joint_a6: {r: 20.0, l: 0.0, km: 10.0}
      joint_a7: {r: 10.0, l: 0.0, km: 10.0}
    
    current_loop_gains: 
      joint_a1: {p: 20.0, i: 0.0, d: 10.0, i_clamp: 10000.0}
      joint_a2: {p: 20.0, i: 0.0, d: 10.0, i_clamp: 10000.0}
      joint_a3: {p: 20.0, i: 0.0, d: 10.0, i_clamp: 10000.0}
      joint_a4: {p: 20.0, i: 0.0, d: 10.0, i_clamp: 10000.0}
      joint_a5: {p: 20.0, i: 0.0, d: 10.0, i_clamp: 10000.0}
      joint_a6: {p: 20.0, i: 0.0, d: 1.0, i_clamp: 500.0}
      joint_a7: {p: 10.0, i: 0.0, d: 1.0, i_clamp: 500.0}

    gear:
      joint_a1: {ratio: 100.0, eff: 1.0}
      joint_a2: {ratio: 100.0, eff: 1.0}
      joint_a3: {ratio: 100.0, eff: 1.0}
      joint_a4: {ratio: 100.0, eff: 1.0}
      joint_a5: {ratio: 100.0, eff: 1.0}
      joint_a6: {ratio: 100.0, eff: 1.0}
      joint_a7: {ratio: 100.0, eff: 1.0}
